name: C++ CI Serial Programs

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, macos-13, ubuntu-24.04]
        qt_version: ['6.9.0']
        include:
        - qt_version: '6.9.0'
          qt_version_major: '6'
          qt_modules: 'qtmultimedia qtserialport'

    steps:
    - uses: actions/checkout@v4
      with:
        path: Arduino-Source
        submodules: 'recursive'
    - uses: actions/checkout@v4
      with:
        repository: 'PokemonAutomation/Packages'
        path: Packages
    - uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt_version }}
        modules: ${{ matrix.qt_modules }}
    - name: Install dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt update
        sudo apt upgrade
        
        echo Install dependencies for openssl
        sudo apt install linux-libc-dev
        
        echo Install dependencies for cairo
        sudo apt install libx11-dev libxft-dev libxext-dev
        
        echo Install dependencies for libepoxy
        sudo apt install libx11-dev libgles2-mesa-dev
        
        echo Install dependencies for libxcrypt
        sudo apt install libltdl-dev
        
        echo Install dependencies for libsystemd
        sudo ${{ env.pythonLocation }}/bin/python3 -m pip install jinja2
        
        echo Install dependencies for at-spi2-core
        sudo apt install libxi-dev libxtst-dev

        echo Install dependencies for gtk3
        sudo apt install libxrandr-dev
        
        sudo apt install autoconf automake libtool
    - name: Install dependencies
      if: startsWith(matrix.os, 'mac')
      run: |
        brew install automake onnxruntime
    - name: Vcpkg setup
      run: |
        cd Arduino-Source
        git submodule foreach git fetch --unshallow || true
    - name: Generate binaries
      run: |
        cd Arduino-Source/SerialPrograms
        mkdir bin
        cd bin
        cmake .. -DQT_MAJOR:STRING=${{ matrix.qt_version_major }} -DCMAKE_TOOLCHAIN_FILE="../../vcpkg/scripts/buildsystems/vcpkg.cmake"
        cmake --build . --config Release --parallel 10
    - name: Copy resources
      if: startsWith(matrix.os, 'windows')
      run: |
        robocopy Packages/SerialPrograms/Resources          Output/Resources /s
        robocopy Packages/PABotBase/PABotBase-Switch        Output/PABotBase /s
        robocopy Arduino-Source/SerialPrograms/bin          Output/Binaries *.dll
        robocopy Arduino-Source/SerialPrograms/bin/Release  Output/Binaries SerialPrograms.exe
        echo https://github.com/${{github.repository}}/commit/${{github.sha}} > Output/version.txt
        write-host "Robocopy exited with exit code:" $lastexitcode
        if ($lastexitcode -eq 1)
        {
          exit 0
        }
        else
        {
          exit 1
        }
    - uses: actions/upload-artifact@v4
      if: startsWith(matrix.os, 'windows')
      with:
        name: Serial Programs for windows (${{ matrix.qt_version }})
        path: Output
